### PR TITLE
Upgrade faye-websockets and eventmachine

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/rndmvr-studio_agent/pull/66

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
I *think* we could require `~> 1.2.0`. It looks like changes from `x.y.1` and `x.y.2` are usually backwards compatible.

**Comment by kris-lab** [comment]
Agree.

@njam please re-review

**Comment by njam** [comment]
lgtm

**Comment by njam** [comment]
While you're at it, could you add docu how to release a new version?

**Comment by kris-lab** [comment]
@njam have a look please

**Comment by kris-lab** [comment]
released

**Pull request merged**
