### PR TITLE
Rtpbroadcast: add "watch-udp"

### PR DESCRIPTION
**Pull request by kris-lab**
Support for https://github.com/cargomedia/janus-gateway-rtpbroadcast#watch-udp

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam have a look

**Comment by njam** [comment]
Add a spec?
Please check rubocop.
Otherwise looks good.

**Comment by njam** [comment]
@kris-lab please double check

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
released

**Pull request merged**
