### PR TITLE
Add "list" action for rtpbroadcast

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
What about quickly restructure to:

```
.
├── client.rb
├── endpoint.rb
├── error.rb
├── plugin
│   ├── rtpbroadcast
│   │   ├── endpoint
│   │   │   ├── list.rb
│   │   │   └── mountpoint.rb
│   │   └── resource
│   │       └── mountpoint.rb
│   └── rtpbroadcast.rb
├── resource
│   ├── plugin.rb
│   └── session.rb
├── resource.rb
├── transport
│   └── websocket.rb
├── transport.rb
└── version.rb
```
I feel bad that list.rb is extending resource.

@kris-lab wdyt?

**Comment by tomaszdurka** [comment]
@kris-lab please review

**Comment by tomaszdurka** [comment]
Paired with @kris-lab

**Comment by kris-lab** [comment]
lgtm

**Pull request merged**
