### PR TITLE
Allow to pass "token" plus additional "channelData"

### PR DESCRIPTION
**Pull request by kris-lab**
Both are strings (json).
- sessionData: Send it in janus' `token` field
- channelData: Send along when `create`ing a plugin resource, like the rtpbroadcast mountpoint (https://github.com/cargomedia/cm-janus/pull/77)

cc @tomaszdurka

### CODE REVIEW

**Comment by kris-lab** [comment]
There are many ways to achieve out goal. The main question: should this extra data be common for each transport? I can imagine that yes! It should be common for http/websocket/rabbit.

I see a few way:
- first which is in PR: it register extra data on the client and attach to each request. Currently only the  session can register that data
- we will not pass data to the client but rather allow to register  callback which would be executed for each `send_transaction` request?
- we could keep data on `session` instance and then `plugin` or `mountpoint` would have to get this and merge to each `send_transaction`

@njam wdyt?

**Comment by njam** [comment]
Tomasz says:
- Rather keep this data on the client directly, as it is theoretically valid for every session of the same connection (ugh). This is how it also is in the JS client. Let's call it `token`?
- On the mountpoint, let's call consistently it `channel_data`

Generally agree with the approach

**Comment by kris-lab** [comment]
In general agree. The problem of keeping data on the `client` is that we pass `transport`  as adapter do it doesn't know to much about parent! This `extra_data` are used by transport only which is easily accessible from `resource` or `plugin` via `client`as it proxy everything to the `transport`. It was the idea to proxy as much as possible. If we store `extra_data` on the client it will complicate thing yes? @tomaszdurka @njam wdyt?

**Comment by njam** [comment]
I would suggest to store an optional `token` on the client. Then the transport would read that `token` from the client whenever sending something, and just send it along.
wdyt?

**Comment by kris-lab** [comment]
How would you access `client` from `transport`? Technically in `ruby`?

**Comment by njam** [comment]
Good point! Can we inject the token in `client.send_transaction`, before calling `transport.send_transaction`?

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- rtpbroadcast/mountpoint.rb: intialize: docu
- resource/session.rb: initialize: I would suggest to move this to `client.initialize` and call it `token`. Because this is a general "janus-gateway" feature, and others might use it like that, and would expect it there (like in the js client).
 - Either `client.initialize(transport, token)` or even `client.initialize(transport, options)`, where `options` is a `Hash` with a `token` key?

**Comment by njam** [comment]
lgtm

**Pull request merged**
